version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    platform: linux/arm64/v8  # Optimized for M1 chip
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - wordpress

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/arm64/v8  # Optimized for M1 chip
    container_name: wordpress_app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress:/var/www/html
    networks:
      - wordpress

  # Nginx Reverse Proxy for HTTPS
  nginx:
    image: nginx:alpine
    platform: linux/arm64/v8  # Optimized for M1 chip
    container_name: wordpress_nginx
    restart: unless-stopped
    ports:
      - "8443:443"  # Custom HTTPS port
      - "8081:80"   # HTTP redirect
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - wordpress

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress:
    driver: bridge